import type { Metadata } from "next"
import { Geist, Geist_Mono, Oswald } from "next/font/google"
import "./globals.css"
import Providers from "@/components/utils/providers"


const oswald = Oswald({
  variable: "--font-oswald",//tailwind?
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} antialiased transition-colors duration-500 h-screen bg-back text-text`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
